### ISSUE TITLE
Usage example in README.rst refers to non-standard Adafruit module

### ISSUE THREAD

**Issue by SAK917** [adafruit/Adafruit_CircuitPython_DisplayIO_SH1107#3]
The **Usage Example** code in README.rst refers to a module possibly used during development?

`Line 5:  import mdroberts1243_displayio_sh1107`

and

`Line 19: display = mdroberts1243_displayio_sh1107.SH1107(display_bus, width=WIDTH, height=HEIGHT)`

I believe the correct reference should be `adafruit_displayio_sh1107`.

I am happy to make whatever change you think would be appropriate and submit a PR if it will help.

**Comment by ladyada** [comment]
oh yeah, woops didnt catch that! a PR would be most welcome :)

**Comment by SAK917** [comment]
This issue has been dealt with in PR#2.
